version: '3'
services:
  cache:
    image: redis
    ports:
      - "6380:6380"
    container_name:
      rusty-db
    command: redis-server --port 6380
  web:
    stdin_open: true  # For using `docker attach` for debugging
    tty: true  # For using `docker attach` for debugging
    build: .
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6380
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_S3_RAW_DATA_BUCKET
      - AWS_DYNAMO_TABLE_SUMMARY
    ports:
      - "8000:8000"
    depends_on:
      - cache
    container_name:
      rusty-dusty
